//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaasFeeGuides.IntegrationTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PostTestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostTestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaasFeeGuides.IntegrationTests.Properties.PostTestData", typeof(PostTestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;Allalin&quot;,
        ///    &quot;TitleContent&quot;: [
        ///      {
        ///        &quot;Id&quot;: &quot;Allalin_Title&quot;,
        ///        &quot;Value&quot;: &quot;ALLALINHORN 4027M&quot;,
        ///        &quot;Locale&quot;: &quot;na&quot;,
        ///        &quot;ContentType&quot;: &quot;Text&quot;
        ///      }
        ///    ],
        ///    &quot;DescriptionContent&quot;: [
        ///      {
        ///        &quot;Id&quot;: &quot;Allalin_Desc&quot;,
        ///        &quot;Value&quot;: &quot;My first 4000m peak! The Allalin is known as one of the easier 4000m peaks in the Alps and offers an unforgetable...&quot;,
        ///        &quot;Locale&quot;: &quot;en&quot;,
        ///        &quot;ContentType&quot;: &quot;Text&quot;
        ///      },
        ///      {
        ///        &quot;Id&quot;: &quot;Allalin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;Allalin&quot;,
        ///    &quot;TitleContent&quot;: [
        ///      {
        ///        &quot;Id&quot;: &quot;Allalin_Title&quot;,
        ///        &quot;Value&quot;: &quot;ALLALINHORN 4027M&quot;,
        ///        &quot;Locale&quot;: &quot;na&quot;,
        ///        &quot;ContentType&quot;: &quot;Text&quot;
        ///      }
        ///    ],
        ///    &quot;DescriptionContent&quot;: [
        ///      {
        ///        &quot;Id&quot;: &quot;Allalin_Desc&quot;,
        ///        &quot;Value&quot;: &quot;My first 4000m peak! The Allalin is known as one of the easier 4000m peaks in the Alps and offers an unforgetable...&quot;,
        ///        &quot;Locale&quot;: &quot;en&quot;,
        ///        &quot;ContentType&quot;: &quot;Text&quot;
        ///      },
        ///      {
        ///        &quot;Id&quot;: &quot;Allalin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivitiesAndSkus {
            get {
                return ResourceManager.GetString("ActivitiesAndSkus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;ActivityName&quot;: &quot;Allalin&quot;,
        ///    &quot;Name&quot;: &quot;AllalinSku&quot;,
        ///    &quot;TitleContent&quot;: [
        ///      {
        ///        &quot;Id&quot;: &quot;AllalinSku_Title&quot;,
        ///        &quot;Value&quot;: &quot;ALLALINHORN 4027M&quot;,
        ///        &quot;Locale&quot;: &quot;na&quot;,
        ///        &quot;ContentType&quot;: &quot;Text&quot;
        ///      }
        ///    ],
        ///    &quot;DescriptionContent&quot;: [
        ///      {
        ///        &quot;Id&quot;: &quot;AllalinSku_Desc&quot;,
        ///        &quot;Value&quot;: &quot;&lt;b&gt;MY FIRST 4000M PEAK!&lt;/b&gt;\r\nThe Allalin is known as one of the easier 4000m peaks in the Alps and offers an unforgetable experience for good hikers which aim higher!\r\n\r\n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivitySkus {
            get {
                return ResourceManager.GetString("ActivitySkus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;Ice axe&quot;,
        ///    &quot;TitleContent&quot;: [
        ///      {
        ///        &quot;Id&quot;: &quot;IceAxeTitle&quot;,
        ///        &quot;Value&quot;: &quot;Ice Axe&quot;,
        ///        &quot;Locale&quot;: &quot;en&quot;,
        ///        &quot;ContentType&quot;: &quot;Text&quot;
        ///      },
        ///      {
        ///        &quot;Id&quot;: &quot;IceAxeTitle&quot;,
        ///        &quot;Value&quot;: &quot;Pickel&quot;,
        ///        &quot;Locale&quot;: &quot;de&quot;,
        ///        &quot;ContentType&quot;: &quot;Text&quot;
        ///      }
        ///    ],
        ///    &quot;RentalPrice&quot;: 10.0,
        ///    &quot;ReplacementPrice&quot;: 150.0
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Climbing Harness&quot;,
        ///    &quot;TitleContent&quot;: [
        ///      {
        ///        &quot;Id&quot;: &quot;HarnessTitle&quot;,
        ///        &quot;Value&quot;: &quot;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Equiptment {
            get {
                return ResourceManager.GetString("Equiptment", resourceCulture);
            }
        }
    }
}
